mailcatcher:
  image: schickling/mailcatcher
  ports:
    - "1080:1080"
  expose:
    - "1025"
elasticsearch:
  image: elasticsearch:1.5.2
  command:
    /scripts/elastic_search
  volumes:
    - ./scripts:/scripts
  ports:
    - "9200:9200"
    - "9300:9300"
  expose:
    - "9200"
db:
  image: mitimes/db
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_DB=mitimes_development
    - POSTGRES_USER=mitimes
  volumes:
    - ../docker-postgresql:/data
  expose:
    - "5432"
redis:
  image: redis
  ports:
    - "6379:6379"
  expose:
    - "6379"
