#!/bin/bash
if ! [ -d /usr/share/elasticsearch/plugins/head ]; then
  echo "Installing mobz head ES tool"
  /usr/share/elasticsearch/bin/plugin -install mobz/elasticsearch-head/1.x
fi
elasticsearch -Des.network.host=0.0.0.0

